I don't believe it

diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -1,68 +1,66 @@
 #!/bin/bash
 
 if [ $# -lt 2 ]; then
-    echo "Usage: $(basename $0) [-f] destdir achieve.."
-    echo '-f forces creation of nonexistent destdir'
-    exit 1
+	echo "Usage: $(basename $0) [-f] destdir achieve.."
+	echo '-f forces creation of nonexistent destdir'
+	exit 1
 fi
 
 if [ "$1" = '-f' ]; then
-    FORCE=1
-    shift
+	FORCE=1
+	shift
 else
-    FORCE=0
+	FORCE=0
 fi
 
 if [ -z "$1" ]; then
-    OUTPUT=.
+	OUTPUT=.
 else
-    OUTPUT="$1"
+	OUTPUT="$1"
 fi
 shift
 
 if [ ! -d "$OUTPUT" ]; then
-    if [ -e "$OUTPUT" ]; then
-        echo "'$OUTPUT' already exists and is not a directory"
-        exit 1
-    elif [ "$FORCE" != "0" ]; then
-        mkdir -p "$OUTPUT"
-    else
-        echo "'$OUTPUT' doesn't exist"
-        exit 1
-    fi
+	if [ -e "$OUTPUT" ]; then
+		echo "'$OUTPUT' already exists and is not a directory"
+		exit 1
+	elif [ "$FORCE" != "0" ]; then
+		mkdir -p "$OUTPUT"
+	else
+		echo "'$OUTPUT' doesn't exist"
+		exit 1
+	fi
 fi
 
 exitcode=0
 
 for file; do
-    if [ ! -f "$file" ]; then
-        echo "'$file' is not a valid file"
-        continue
-    fi
+	if [ ! -f "$file" ]; then
+		echo "'$file' is not a valid file"
+		continue
+	fi
 
-    FULL=$(readlink -f "$file")
+	FULL=$(readlink -f "$file")
 
-    cd "$OUTPUT"
+	cd "$OUTPUT"
 
-    case "$file" in
-        *.tar.bz2) tar xvjf "$FULL" ;;
-        *.tar.gz) tar xvzf "$FULL" ;;
-        *.bz2) bunzip2 "$FULL" ;;
-        *.rar) unrar x "$FULL" ;;
-        *.gz) gunzip "$FULL" ;;
-        *.tar) tar xvf "$FULL" ;;
-        *.tbz2) tar xvjf "$FULL" ;;
-        *.tgz) tar xvzf "$FULL" ;;
-        *.war) unzip "$FULL" ;;
-        *.zip) unzip "$FULL" ;;
-        *.Z) uncompress "$FULL" ;;
-        *.7z) 7z x "$FULL" ;;
-        *.tar.lzma) tar xf "$FULL" ;;
-        *.tar.xz) tar xf "$FULL" ;;
-        *) echo "'$file' cannot be extracted via this script"; exitcode=1 ;;
-    esac
+	case "$file" in
+		*.tar|*.tar.bz2|*.tbz2|*.tar.gz|*.tgz|*.tar.lz|*.tlz|*.tar.lzma|*.tar.xz|*.txz|*.tar.Z|*.tar.zst) tar xvf "$FULL" ;;
+		*.bz2) bunzip2 "$FULL" ;;
+		*.cab) cabextract "$FULL" ;;
+		*.gz) gunzip -k "$FULL" ;;
+		*.lz4) unlz4 "$FULL" ;;
+		*.lzma) unlzma "$FULL" ;;
+		*.xz) unxz "$FULL" ;;
+		*.rar) unrar x "$FULL" ;;
+		*.apk|*.jar|*.war|*.zip) unzip "$FULL" ;;
+		*.z) uncompress "$FULL" ;;
+		*.zst) unzstd "$FULL" ;;
+		*.7z) 7z x "$FULL" ;;
+		*) echo "'$file' cannot be extracted via this script"; exitcode=1 ;;
+	esac
 
-    cd "$OLDPWD"
+	cd "$OLDPWD"
 done
 
 exit $exitcode
